// This file was generated by counterfeiter
package listenersfakes

import (
	"net"
	"sync"
)

type FakeListener struct {
	AcceptStub        func() (net.Conn, error)
	acceptMutex       sync.RWMutex
	acceptArgsForCall []struct{}
	acceptReturns     struct {
		result1 net.Conn
		result2 error
	}
	CloseStub        func() error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct{}
	closeReturns     struct {
		result1 error
	}
	AddrStub        func() net.Addr
	addrMutex       sync.RWMutex
	addrArgsForCall []struct{}
	addrReturns     struct {
		result1 net.Addr
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeListener) Accept() (net.Conn, error) {
	fake.acceptMutex.Lock()
	fake.acceptArgsForCall = append(fake.acceptArgsForCall, struct{}{})
	fake.recordInvocation("Accept", []interface{}{})
	fake.acceptMutex.Unlock()
	if fake.AcceptStub != nil {
		return fake.AcceptStub()
	} else {
		return fake.acceptReturns.result1, fake.acceptReturns.result2
	}
}

func (fake *FakeListener) AcceptCallCount() int {
	fake.acceptMutex.RLock()
	defer fake.acceptMutex.RUnlock()
	return len(fake.acceptArgsForCall)
}

func (fake *FakeListener) AcceptReturns(result1 net.Conn, result2 error) {
	fake.AcceptStub = nil
	fake.acceptReturns = struct {
		result1 net.Conn
		result2 error
	}{result1, result2}
}

func (fake *FakeListener) Close() error {
	fake.closeMutex.Lock()
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct{}{})
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if fake.CloseStub != nil {
		return fake.CloseStub()
	} else {
		return fake.closeReturns.result1
	}
}

func (fake *FakeListener) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *FakeListener) CloseReturns(result1 error) {
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeListener) Addr() net.Addr {
	fake.addrMutex.Lock()
	fake.addrArgsForCall = append(fake.addrArgsForCall, struct{}{})
	fake.recordInvocation("Addr", []interface{}{})
	fake.addrMutex.Unlock()
	if fake.AddrStub != nil {
		return fake.AddrStub()
	} else {
		return fake.addrReturns.result1
	}
}

func (fake *FakeListener) AddrCallCount() int {
	fake.addrMutex.RLock()
	defer fake.addrMutex.RUnlock()
	return len(fake.addrArgsForCall)
}

func (fake *FakeListener) AddrReturns(result1 net.Addr) {
	fake.AddrStub = nil
	fake.addrReturns = struct {
		result1 net.Addr
	}{result1}
}

func (fake *FakeListener) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.acceptMutex.RLock()
	defer fake.acceptMutex.RUnlock()
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	fake.addrMutex.RLock()
	defer fake.addrMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeListener) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ net.Listener = new(FakeListener)
